###############################################################################
# Alacritty Configuration File (TOML)
#
# A comprehensive configuration for a comfortable terminal experience.
# Uses the Hack font (with fallback to Noto Sans) at a larger size.
#
# Save this file as: ~/.config/alacritty/alacritty.toml
###############################################################################

# -----------------------------------------------------------------------------
# Font Configuration
# -----------------------------------------------------------------------------
[font]
# Primary font configuration: family, style, and size.
normal = { family = "Hack", style = "Regular" }
bold   = { family = "Hack", style = "Bold" }
italic = { family = "Hack", style = "Italic" }
size   = 14.0
fallback = ["Noto Sans"]

# -----------------------------------------------------------------------------
# Window & Terminal Settings
# -----------------------------------------------------------------------------
[window]
title = "Alacritty"
dynamic_title = true

[window.dimensions]
columns = 120
lines   = 30

# Available options: "full", "none", "transparent"
decorations = "full"

# -----------------------------------------------------------------------------
# Color Scheme
# -----------------------------------------------------------------------------
[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.normal]
black   = "#1d1f21"
red     = "#cc6666"
green   = "#b5bd68"
yellow  = "#f0c674"
blue    = "#81a2be"
magenta = "#b294bb"
cyan    = "#8abeb7"
white   = "#c5c8c6"

[colors.bright]
black   = "#666666"
red     = "#d54e53"
green   = "#b9ca4a"
yellow  = "#e7c547"
blue    = "#7aa6da"
magenta = "#c397d8"
cyan    = "#70c0b1"
white   = "#eaeaea"

# -----------------------------------------------------------------------------
# Cursor Configuration
# -----------------------------------------------------------------------------
[cursor]
# Options: "Block", "Underline", or "Beam"
style = "Beam"
unfocused_hollow = true

# -----------------------------------------------------------------------------
# Scrolling & Smooth Scrolling
# -----------------------------------------------------------------------------
[scrolling]
# Maximum number of lines to retain in the scrollback buffer.
history = 1000000
# Scroll multiplier for faster scrolling.
multiplier = 3

# -----------------------------------------------------------------------------
# Key Bindings
# -----------------------------------------------------------------------------
# Alacritty does not support tabs; the key bindings below cover clipboard and quit operations.
[[key_bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[key_bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[key_bindings]]
key = "Q"
mods = "Control"
action = "Quit"

[[key_bindings]]
key = "F"
mods = "Control"
action = "SearchForward"

[[key_bindings]]
key = "B"
mods = "Control"
action = "SearchBackward"

# -----------------------------------------------------------------------------
# Miscellaneous Options
# -----------------------------------------------------------------------------
# Automatically reload configuration file when it is changed.
live_config_reload = true

###############################################################################
# End of Configuration
###############################################################################
